sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kattinum/docker-react -f Dockerfile.dev .

script:
  - docker run kattinum/docker-react npm run test -- --coverage
